# config.yml

lang: "fr"

#check loop time in seconds
iteration-time: 5

# duration of booster on single purchase
booster-time: 1000

# Max Level
max_spawner_level: 3

# you can add/customise more level
upgrade_levels:
  1:
#    default level (cant be changed)
#    spawn_delay: 20
#    min_spawn_delay: 200
#    max_spawn_delay: 800
#    spawn_count: 4
#    max_nearby_entities: 6
#    required_player_range: 16

  2:
    spawn_delay: 15
    min_spawn_delay: 160
    max_spawn_delay: 200
    spawn_count: 8
    max_nearby_entities: 10
    required_player_range: 20
    money: 2
  3:
    spawn_delay: 10
    min_spawn_delay: 120
    max_spawn_delay: 140
    spawn_count: 10
    max_nearby_entities: 14
    required_player_range: 26
    money: 3

  # this is unique level for booster only
  1000:
    spawn_delay: 10
    min_spawn_delay: 99
    max_spawn_delay: 101
    spawn_count: 12
    max_nearby_entities: 20
    required_player_range: 26
    money: 4