name: sigma
version: '1.0-SNAPSHOT'
main: org.first.jayesh.Sigma
api-version: '1.20'
depend: [Vault]


commands:
  ccheck:
  cstat:
  crestore:
  ccgui:
  RestoreAllSpawnerData:
  SeeAllSpawnerData:
  leveledSpawner: